name: flutter_treemap_testbed
description: A new Flutter project.
version: 1.0.0
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_treemap

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  syncfusion_flutter_treemap:
    path: ../syncfusion_flutter_treemap/

  syncfusion_flutter_core:
    path: D:\Sources\FlutterCore\syncfusion_flutter_core
#    git:
#      url: https://buildautomation:Coolcomp299@gitlab.syncfusion.com/essential-studio/flutter-core
#      path: syncfusion_flutter_core
#      branch: development
#      ref: development

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
